WebApp/Areas/Admin/Controllers/DesignCategoryController.cs
using Repositories.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewModels;

namespace WebApp.Areas.Admin.Controllers
{
    public class DesignCategoryController : BasedController
    {
        private readonly IDesignCategoryRepository _designCategoryRepository;

        public DesignCategoryController(IDesignCategoryRepository designCategoryRepository)
        {
            _designCategoryRepository = designCategoryRepository;
        }

        // GET: Admin/DesignCategory
        public ActionResult Index(int page = 1)
        {
            var list = _designCategoryRepository.GetList(page);
            return View(list);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DesignCategoryVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _designCategoryRepository.Create(model);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(model);
                }
            }
            catch(Exception ex)
            {
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult Edit(long id)
        {
            var detail = _designCategoryRepository.DetailViewModel(id);
            return View(detail);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DesignCategoryVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _designCategoryRepository.Edit(model);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(model);
                }
            }
            catch (Exception ex)
            {
                return View(model);
            }
        }

        [HttpPost]
        public JsonResult Delete(long id)
        {
            try
            {
                if(id == 0)
                {
                    return Json(new { Staus = false, Message = "Có lỗi sảy ra, vui lòng thử lại sau" }, JsonRequestBehavior.AllowGet);
                }
                _designCategoryRepository.Delete(id);
                return Json(new { Status = true }, JsonRequestBehavior.AllowGet);
            }
            catch(Exception ex)
            {
                return Json(new { Staus = false, Message = "Có lỗi sảy ra, vui lòng thử lại sau" }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

WebApp/Areas/Admin/Views/DesignCategory/Create.cshtml
@model ViewModels.DesignCategoryVM

@{
    ViewBag.Title = "Quản lý danh mục giao diện";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section Title{
    @ViewBag.Title
}


@using (Html.BeginForm("Create", "DesignCategory", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-success">Thêm mới</button>
                @Html.ActionLink("Quay lại", "Index")
            </div>
        </div>
    </div>
}

WebApp/Areas/Admin/Views/DesignCategory/Edit.cshtml
@model ViewModels.DesignCategoryVM

@{
    ViewBag.Title = "Quản lý danh mục giao diện";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section Title{
    @ViewBag.Title
}


@using (Html.BeginForm("Edit", "DesignCategory", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-success">Sửa</button>
                @Html.ActionLink("Quay lại", "Index")
            </div>
        </div>
    </div>
}

WebApp/Areas/Admin/Views/DesignCategory/Index.cshtml
@model IEnumerable<ViewModels.DesignCategoryVM>
@using X.PagedList;
@using X.PagedList.Mvc;
@{
    ViewBag.Title = "Quản lý danh mục giao diện";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section Title{
    @ViewBag.Title
}

<p>
    @Html.ActionLink("Thêm mới", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Tên danh mục
        </th>
        <th>
            Trạng thái
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Common.CommonStatus.StatusDisplay[item.Status]
            </td>
            <td>
                <button type="button" class="btn btn-success">
                    @Html.ActionLink("Sửa", "Edit", new { id = item.Id })
                </button>
                <button type="button" class="btn btn-danger delete" data-id="@item.Id">
                    Xóa
                </button>
            </td>
        </tr>
    }
</table>

<nav aria-label="Page navigation">
    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }), new PagedListRenderOptions()
    {
           UlElementClasses = new string[] { "pagination pagination-circle" },
           LiElementClasses = new string[] { "page-item" },
           PageClasses = new string[] { "page-link" }
    })
</nav>

@section scripts{
    <script src="~/Areas/Admin/Libraries/js/designCategory.js"></script>
}