WebApp/Areas/Admin/Controllers/FoodCategoryController.cs
using Repositories.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewModels;

namespace WebApp.Areas.Admin.Controllers
{
    public class FoodCategoryController : BasedController
    {
        private readonly IFoodCategoryRepository _foodCategoryRepository;

        public FoodCategoryController(IFoodCategoryRepository foodCategoryRepository)
        {
            _foodCategoryRepository = foodCategoryRepository;
        }

        // GET: Admin/FoodCategory
        public ActionResult Index(string searchKey = "", bool? status = null, int page = 1, int pageSize = 20)
        {
            var list = _foodCategoryRepository.GetList(searchKey, status, page, pageSize);
            return View(list);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(FoodCategoryVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _foodCategoryRepository.Create(model);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(model);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Có lỗi xảy ra, vui lòng thử lại");
                return View(model);
            }
        }

        [HttpPost]
        public JsonResult Delete(long id)
        {
            try
            {
                _foodCategoryRepository.Delete(id);
                return Json(new { Status = true }, JsonRequestBehavior.AllowGet);
            }
            catch(Exception ex)
            {
                return Json(new { Status = false, Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

WebApp/Areas/Admin/Views/FoodCategory/Create.cshtml
@model ViewModels.FoodCategoryVM

@{
    ViewBag.Title = "Quản lý danh mục món ăn";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section Title{
    @ViewBag.Title
}

@using (Html.BeginForm("Create", "FoodCategory", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
                @Html.ActionLink("Quay lại", "Index")
            </div>
        </div>
    </div>
}

WebApp/Areas/Admin/Views/FoodCategory/Index.cshtml
@model IEnumerable<ViewModels.FoodCategoryVM>
@using X.PagedList;
@using X.PagedList.Mvc;

@{
    ViewBag.Title = "Quản lý danh mục món ăn";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section Title{
    @ViewBag.Title
}

<p>
    @Html.ActionLink("Thêm mới", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Tên danh mục
        </th>
        <th>
            Trạng thái
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Common.CommonStatus.StatusDisplay[item.Status]
            </td>
            <td>
                <button type="button" data-id="@item.Id" class="btn btn-danger delete">
                    Xóa
                </button>
            </td>
        </tr>
    }
</table>

<nav aria-label="Page navigation">
    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }), new PagedListRenderOptions()
    {
           UlElementClasses = new string[] { "pagination pagination-circle" },
           LiElementClasses = new string[] { "page-item" },
           PageClasses = new string[] { "page-link" }
    })
</nav>

@section scripts{
    <script src="~/Areas/Admin/Libraries/js/foodCategory.js"></script>
}