WebApp/Areas/Admin/Controllers/HotMenuController.cs
using Repositories.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewModels;

namespace WebApp.Areas.Admin.Controllers
{
    public class HotMenuController : BasedController
    {
        private readonly IHotMenuRepository _hotMenuRepository;
        private readonly IFoodRepository _foodRepository;

        public HotMenuController(IHotMenuRepository hotMenuRepository, IFoodRepository foodRepository)
        {
            _hotMenuRepository = hotMenuRepository;
            _foodRepository = foodRepository;
        }

        // GET: Admin/Menu
        public ActionResult Index(int page = 1, int pageSize = 10)
        {
            var list = _hotMenuRepository.GetList(page, pageSize);
            return View(list);
        }

        [HttpGet]
        public ActionResult Create()
        {
            SetDropdow(Guid.Empty, Guid.Empty, Guid.Empty, Guid.Empty, Guid.Empty, Guid.Empty);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HotMenuVM model)
        {
            try
            {
                SetDropdow(Guid.Empty, Guid.Empty, Guid.Empty, Guid.Empty, Guid.Empty, Guid.Empty);
                if (ModelState.IsValid)
                {
                    _hotMenuRepository.Create(model);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(model);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Có lỗi xảy ra, vui lòng thử lại sau");
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            var detail = _hotMenuRepository.DetailViewModel(id);
            SetDropdow(detail.FoodId1, detail.FoodId2, detail.FoodId3, detail.FoodId4, detail.FoodId5, detail.FoodId6);
            return View(detail);
        }

        [HttpPost]
        public ActionResult Edit(HotMenuVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _hotMenuRepository.Edit(model);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(model);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Có lỗi xảy ra, vui lòng thử lại sau");
                return View(model);
            }
        }

        [HttpPost]
        public JsonResult SetActive(Guid id)
        {
            try
            {
                _hotMenuRepository.SetActive(id);
                return Json(new { Status = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { Status = false, Message = "Có lỗi xảy ra, vui lòng thử lại sau" }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Details(Guid id)
        {
            var detail = _hotMenuRepository.DetailViewModel(id);
            return View(detail);
        }

        public void SetDropdow(Guid id1, Guid id2, Guid id3, Guid id4, Guid id5, Guid id6)
        {
            var list = _foodRepository.GetList();
            var selectList = new SelectList(list, "Id", "Name");

            if (id1 == null)
                ViewBag.FoodId1 = selectList;
            else
                ViewBag.FoodId1 = new SelectList(list, "Id", "Name", id1);

            if (id2 == null)
                ViewBag.FoodId2 = selectList;
            else
                ViewBag.FoodId2 = new SelectList(list, "Id", "Name", id2);

            if (id3 == null)
                ViewBag.FoodId3 = selectList;
            else
                ViewBag.FoodId3 = new SelectList(list, "Id", "Name", id3);

            if (id4 == null)
                ViewBag.FoodId4 = selectList;
            else
                ViewBag.FoodId4 = new SelectList(list, "Id", "Name", id4);

            if (id5 == null)
                ViewBag.FoodId5 = selectList;
            else
                ViewBag.FoodId5 = new SelectList(list, "Id", "Name", id5);

            if (id1 == null)
                ViewBag.FoodId6 = selectList;
            else
                ViewBag.FoodId6 = new SelectList(list, "Id", "Name", id6);
        }
    }
}

WebApp/Areas/Admin/Views/HotMenu/Create.cshtml
@model ViewModels.HotMenuVM

@{
    ViewBag.Title = "Quản lý Hot menu";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section Title{
    @ViewBag.Title
}

@using (Html.BeginForm("Create", "HotMenu", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FoodId1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FoodId1, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FoodId1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FoodId2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FoodId2, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FoodId2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FoodId3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FoodId3, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FoodId3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FoodId4, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FoodId4, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FoodId4, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FoodId5, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FoodId5, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FoodId5, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FoodId6, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FoodId6, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FoodId6, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-primary">Thêm mới</button>
                @Html.ActionLink("Quay lại", "Index")
            </div>

        </div>
    </div>
}

WebApp/Areas/Admin/Views/HotMenu/Details.cshtml
@model ViewModels.HotMenuVM

@{
    ViewBag.Title = "Quản lý Hot menu";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section Title{
    @ViewBag.Title
}


<table class="table">
    <tr>
        <th>
            Stt
        </th>
        <th>
            Tên món ăn
        </th>
        <th style="width: 300px">
            Mô tả món ăn
        </th>
        <th>
            Giá tiền
        </th>
        <th>
            Hình ảnh
        </th>
        <th>
            Danh mục
        </th>
    </tr>

    <tr>
        <td>1</td>
        <td>
            @Model.Food.Name
        </td>
        <td>
            @Model.Food.Description
        </td>
        <td>
            @Model.Food.PriceDisplay
        </td>
        <td>
            <img src="~/Areas/Admin/Libraries/images/@Model.Food.Image" style="width: 150px; height: auto">
        </td>
        <td>
            @Model.Food.FoodCategory.Name
        </td>
    </tr>

    <tr>
        <td>2</td>
        <td>
            @Model.Food1.Name
        </td>
        <td>
            @Model.Food1.Description
        </td>
        <td>
            @Model.Food1.PriceDisplay
        </td>
        <td>
            <img src="~/Areas/Admin/Libraries/images/@Model.Food.Image" style="width: 150px; height: auto">
        </td>
        <td>
            @Model.Food1.FoodCategory.Name
        </td>
    </tr>

    <tr>
        <td>3</td>
        <td>
            @Model.Food2.Name
        </td>
        <td>
            @Model.Food2.Description
        </td>
        <td>
            @Model.Food2.PriceDisplay
        </td>
        <td>
            <img src="~/Areas/Admin/Libraries/images/@Model.Food2.Image" style="width: 150px; height: auto">
        </td>
        <td>
            @Model.Food2.FoodCategory.Name
        </td>
    </tr>

    <tr>
        <td>4</td>
        <td>
            @Model.Food3.Name
        </td>
        <td>
            @Model.Food3.Description
        </td>
        <td>
            @Model.Food3.PriceDisplay
        </td>
        <td>
            <img src="~/Areas/Admin/Libraries/images/@Model.Food3.Image" style="width: 150px; height: auto">
        </td>
        <td>
            @Model.Food3.FoodCategory.Name
        </td>
    </tr>

    <tr>
        <td>5</td>
        <td>
            @Model.Food4.Name
        </td>
        <td>
            @Model.Food4.Description
        </td>
        <td>
            @Model.Food4.PriceDisplay
        </td>
        <td>
            <img src="~/Areas/Admin/Libraries/images/@Model.Food4.Image" style="width: 150px; height: auto">
        </td>
        <td>
            @Model.Food4.FoodCategory.Name
        </td>
    </tr>

    <tr>
        <td>6</td>
        <td>
            @Model.Food5.Name
        </td>
        <td>
            @Model.Food5.Description
        </td>
        <td>
            @Model.Food5.PriceDisplay
        </td>
        <td>
            <img src="~/Areas/Admin/Libraries/images/@Model.Food5.Image" style="width: 150px; height: auto">
        </td>
        <td>
            @Model.Food5.FoodCategory.Name
        </td>
    </tr>

</table>

@Html.ActionLink("Quay lại", "Index")

WebApp/Areas/Admin/Views/HotMenu/Edit.cshtml
@model ViewModels.HotMenuVM

@{
    ViewBag.Title = "Quản lý Hot menu";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section Title{
    @ViewBag.Title
}

@using (Html.BeginForm("Edit", "HotMenu", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FoodId1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FoodId1, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FoodId1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FoodId2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FoodId2, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FoodId2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FoodId3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FoodId3, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FoodId3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FoodId4, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FoodId4, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FoodId4, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FoodId5, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FoodId5, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FoodId5, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FoodId6, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FoodId6, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FoodId6, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-primary">Sửa</button>
                @Html.ActionLink("Quay lại", "Index")
            </div>

        </div>
    </div>
}

WebApp/Areas/Admin/Views/HotMenu/Index.cshtml
@model IEnumerable<ViewModels.HotMenuVM>
@using X.PagedList;
@using X.PagedList.Mvc;
@{
    ViewBag.Title = "Quản lý Hot menu";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section Title{
    @ViewBag.Title
}
<p>
    @Html.ActionLink("Thêm mới", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Tên món ăn 1
        </th>
        <th>
            Tên món ăn 2
        </th>
        <th>
            Tên món ăn 3
        </th>
        <th>
            Tên món ăn 4
        </th>
        <th>
            Tên món ăn 5
        </th>
        <th>
            Tên món ăn 6
        </th>
        <th>
            Status
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Food.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Food1.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Food2.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Food3.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Food4.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Food5.Name)
            </td>
            <td>
                @Common.CommonStatus.StatusDisplay[item.Status]
            </td>
            <td>
                <button type="button" data-id="@item.Id" class="btn btn-info">
                    @Html.ActionLink("Chi tiết", "Details", new { id = item.Id })
                </button>
                @if (item.Status == Common.CommonStatus.Active)
                {
                    <button type="button" data-id="@item.Id" class="btn btn-dark">
                        @Html.ActionLink("Sửa", "Edit", new { id = item.Id })
                    </button>
                }
                else
                {
                    <button type="button" data-id="@item.Id" class="btn btn-primary set-active">
                        Áp dụng
                    </button>
                }
            </td>
        </tr>
    }
</table>

<nav aria-label="Page navigation">
    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }), new PagedListRenderOptions()
    {
           UlElementClasses = new string[] { "pagination pagination-circle" },
           LiElementClasses = new string[] { "page-item" },
           PageClasses = new string[] { "page-link" }
    })
</nav>

@section scripts{
    <script src="~/Areas/Admin/Libraries/js/hotMenu.js"></script>
}